# commit to be tagged for the new release
commit = "HEAD"

project_name = "omni-audit-log-exporter"
github_repo = "siderolabs/omni-audit-log-exporter"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
